print("-----not-----")
a = True
c = not  a
print("data a =",a)
print("data c =",c)
print("-----or-----")
a = True
b = False
c = a or b
print(a,"or",b,"=",c)
a = True
b = True
c = a or b
print(a,"or",b,"=",c)
a = False
b = False
c = a or b
print(a,"or",b,"=",c)
a = False
b = True
c = a or b
print(a,"or",b,"=",c)
print("-----and-----")
a = True
b = False
c = a and b
print(a,"and",b,"=",c)
a = True
b = True
c = a and b
print(a,"and",b,"=",c)
a = False
b = False
c = a and b
print(a,"and",b,"=",c)
a = False
b = True
c = a and b
print(a,"and",b,"=",c)
print("-----xor-----")
a = True
b = False
c = a ^ b
print(a,"^",b,"=",c)
a = True
b = True
c = a ^ b
print(a,"^",b,"=",c)
a = False
b = False
c = a ^ b
print(a,"^",b,"=",c)
a = False
b = True
c = a ^ b
print(a,"^",b,"=",c)